name: daily_motivation_api
description: Async API client for Daily Motivation Terminal.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: '^3.8.1'

dependencies:
  http: ^1.2.0
  logging: ^1.2.0
  terminal_colors:
    workspace: true

dev_dependencies:
  test: ^1.24.0
  lints: ^6.0.0
